import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

export class DocumentAgent {
  constructor() {
    this.name = 'DocumentAgent';
    this.capabilities = ['pdf', 'docx', 'reports', 'documents'];
  }

  async execute(command, context) {
    console.log(`📄 ${this.name} executing: ${command}`);

    const docType = this.detectDocumentType(command);

    switch (docType) {
      case 'pdf':
        return await this.generatePDF(command, context);
      case 'report':
        return await this.generateReport(command, context);
      default:
        return await this.generateGenericDocument(command, context);
    }
  }

  detectDocumentType(command) {
    const lower = command.toLowerCase();
    if (lower.includes('pdf')) return 'pdf';
    if (lower.includes('report')) return 'report';
    return 'generic';
  }

  async generatePDF(command, context) {
    try {
      const pdfDoc = await PDFDocument.create();
      const page = pdfDoc.addPage([600, 800]);
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

      // Title
      page.drawText('Universal AI Assistant Report', {
        x: 50,
        y: 750,
        size: 24,
        font: boldFont,
        color: rgb(0, 0, 0)
      });

      // Content
      const content = context.content || 'Generated by Universal AI Assistant';
      const lines = this.wrapText(content, 500);
      
      let yPosition = 700;
      lines.forEach(line => {
        page.drawText(line, {
          x: 50,
          y: yPosition,
          size: 12,
          font,
          color: rgb(0, 0, 0)
        });
        yPosition -= 20;
      });

      // Footer
      page.drawText(`Generated: ${new Date().toLocaleString()}`, {
        x: 50,
        y: 50,
        size: 10,
        font,
        color: rgb(0.5, 0.5, 0.5)
      });

      const pdfBytes = await pdfDoc.save();
      const base64 = Buffer.from(pdfBytes).toString('base64');

      return {
        success: true,
        type: 'pdf',
        data: base64,
        filename: `report-${Date.now()}.pdf`,
        message: 'PDF generated successfully'
      };
    } catch (error) {
      return {
        success: false,
        error: error.message
      };
    }
  }

  async generateReport(command, context) {
    // Generate comprehensive report
    return await this.generatePDF(command, {
      ...context,
      content: this.formatReportContent(context)
    });
  }

  formatReportContent(context) {
    return `
EXECUTIVE SUMMARY
${context.summary || 'No summary provided'}

DETAILS
${context.details || 'No details provided'}

CONCLUSION
${context.conclusion || 'Report generated by Universal AI Assistant'}
    `.trim();
  }

  wrapText(text, maxWidth) {
    const words = text.split(' ');
    const lines = [];
    let currentLine = '';

    words.forEach(word => {
      if ((currentLine + word).length < maxWidth / 6) {
        currentLine += word + ' ';
      } else {
        lines.push(currentLine.trim());
        currentLine = word + ' ';
      }
    });

    if (currentLine) lines.push(currentLine.trim());
    return lines;
  }

  async generateGenericDocument(command, context) {
    return {
      success: true,
      type: 'document',
      message: 'Document generation completed'
    };
  }
}
